name-template: $RESOLVED_VERSION
tag-template: $RESOLVED_VERSION
change-template: * $TITLE (#$NUMBER) @$AUTHOR
categories:
  - title: 🚀 Major Changes
    labels:
      - major # c6476b
  - title: ⚡ Minor Changes
    labels:
      - feature # 006b75
      - enhancement # ededed
      - refactoring
  - title: 🐛 Bug Fixes
    labels:
      - bug # fbca04
      - fix
      - bugfix
  - title: 🔚 Deprecations
    labels:
      - deprecated # fef2c0
exclude-labels:
  - bot:chronographer:skip
  - skip-changelog
version-resolver:
  major:
    labels:
      - major
  minor:
    labels:
      - minor
      - feature
      - enhancement
      - refactoring
  patch:
    labels:
      - patch
      - bug
      - deprecated
  default: patch
exclude-contributors:
  - dependabot
  - pre-commit-ci
autolabeler:
  - label: skip-changelog
    title:
      - "/pre-commit autoupdate/"
    body:
      - "/type: chore/i"
    branch:
      - "/^chore/i"
  - label: bug
    branch:
      - "/^fix/i"
    body:
      - "/type: fix/i"
  - label: feature
    title:
      - "/^(feat|feature)/i"
    body:
      - "/type: feature/i"
  - label: deprecated
    title:
      - "/^deprecat(ed|ion)/i"
    body:
      - "/type: deprecat(ed|ion)/i"
template: |
  $CHANGES
