---
name-template: "$NEXT_{PATCH,MINOR,MAJOR}_VERSION"
tag-template: "$NEXT_{PATCH,MINOR,MAJOR}_VERSION"
change-template: "* $TITLE @$AUTHOR (#$NUMBER)"
version-resolver:
  major:
    labels:
      - major
  minor:
    labels:
      - minor
  patch:
    labels:
      - patch
  default: patch
template: |
  ## Changes

  $CHANGES
