name-template: "$RESOLVED_VERSION"
tag-template: "$RESOLVED_VERSION"
change-template: "* $TITLE (#$NUMBER) @$AUTHOR"
categories:
  - title: "⬆️ Major Changes"
    labels: [major, breaking]
  - title: "🚀 New"
    labels: [feature, enhancement]
  - title: "🐛 Bug Fixes"
    labels: [bug, fix]
  - title: "🔚 Deprecations"
    label: [deprecated]
exclude-labels:
  - skip-changelog
version-resolver:
  major:
    labels:
      - "type: major"
      - "type: breaking"
  minor:
    labels:
      - "type: feature"
      - "type: enhancement"
  patch:
    labels:
      - "type: bug"
      - "type: chore"
      - "type: deprecated"
      - "type: dependencies"
      - "type: documentation"
      - "type: maintenance"
      - "type: security"
      - "type: refactoring"
  default: patch
exclude-contributors: [dependabot]
autolabeler:
  - label: bug
    branch: [ "/^(hot)?fix\/.+/" ]
    title: [ "/^fix:/" ]
  - label: deprecated
    title: ["/deprecat(ed|ion)/i"]
  - label: dependencies
    title: ["/dependenc(y|ies)/i"]
  - label: documentation
    title: ["/^docs:/", "/documentation/i"]
    files: ["*.md", "*.rst"]
  - label: feature
    branch: [ "/^feat(ure)?\/.+/" ]
    title: ["/^feat(ure)?:/"]
  - label: refactoring
    title: ["/^refactor:/"]
  - label: skip-changelog
    title: ["/pre-commit autoupdate/"]
template: |
  $CHANGES
