---
name: CI

on:
  push:
    branches: [ master ]
    tags: [ "[0-9]+.[0-9]+.[0-9]+*" ]
  pull_request:
    branches: [ master ]

jobs:

  linters:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest ]
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/poetry-setup
        with:
          python-version: "3.9"
          os: ${{ matrix.os }}
      - name: Run linter with tox
        shell: bash
        run: tox -e lint

  tests:
    name: ${{ matrix.os }}/${{ matrix.python-version }}
    runs-on: ${{ matrix.os }}
    continue-on-error: ${{ matrix.experimental }}
    strategy:
      matrix:
        os: [ ubuntu-latest, macos-latest, windows-latest ]
        python-version: [ "3.9", "3.10" ]
        experimental: [ false ]
      fail-fast: false
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/poetry-setup
        with:
          python-version: ${{ matrix.python-version }}
          os: ${{ matrix.os }}
      - name: Run test suite with tox
        shell: bash
        run: tox -e py -- -p no:sugar -p no:warnings -q

  coverage:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest ]
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/poetry-setup
        with:
          python-version: "3.9"
          os: ${{ matrix.os }}
      - name: Run coverage with tox
        shell: bash
        run: tox -e coverage -- -p no:sugar -p no:warnings -q
      - name: Submit coverage to codecov
        uses: codecov/codecov-action@v3

  release-draft:
    needs:
      - linters
      - tests
      - coverage
    uses: ./.github/workflows/release-drafter.yaml

  publish:
    if: |
      github.event_name == 'push'
      && startsWith(github.event.ref, 'refs/tags')
    needs: [ release-draft ]
    uses: ./.github/workflows/release.yaml
