---
name: Release

on:
  workflow_call:

jobs:

  github-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: release-drafter/release-drafter@v5
        with:
          publish: True
        env:
          GITHUB_TOKEN: ${{ github.token }}

  pypi-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/poetry-setup
        with:
          python-version: "3.9"
      - name: Build & publish with poetry
        run: poetry publish --build -u $PYPI_USERNAME -p $PYPI_PASSWORD
        env:
          PYPI_USERNAME: __token__
          PYPI_PASSWORD: ${{ secrets.PYPI_TOKEN }}
