---
name: triage

on:
  pull_request:
    types: [opened, reopened, labeled, unlabeled, synchronize]
  pull_request_target:
    types: [opened, reopened, labeled, unlabeled, synchronize]

jobs:
  labels:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      # Use of release drafter action for adding semantic labels based on
      # either title, body or source branch name
      - name: Apply labeling
        uses: release-drafter/release-drafter@v5
        with:
          disable-autolabeler: false
          disable-releaser: true
          config-name: release-drafter.yaml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Ensure that one of the required labels is present and none of the undesired is absent
      # See https://github.com/jesusvasquez333/verify-pr-label-action
      - name: Verify PR label action
        uses: jesusvasquez333/verify-pr-label-action@v1.4.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          valid-labels: "bug, enhancement, feature, refactoring, major, deprecated, skip-changelog"
          invalid-labels: "help wanted, invalid, feedback-needed, incomplete"
          pull-request-number: ${{ github.event.pull_request.number }}
          disable-reviews: true

      - name: Update release notes if this is already merged
        if: github.event.pull_request.merged == true
        uses: release-drafter/release-drafter@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
